name: test_python_mysql
services:
    api:
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            - PYTHONUNBUFFERED=1
            - MYSQL_HOST=db
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpassword
            - MYSQL_DATABASE=testdb
        ports:
            - "5000:5000"
        volumes:
        - "C:\\Software\\Docker\\test_python_mysql\\logs:/app/sslogs"
        networks:
            - ss-network
        depends_on:
            - db
    db:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_DATABASE=testdb
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpassword
        ports:
            - "3310:3306"
        volumes:
            - ./db_data:/var/lib/mysql
        networks:
            - ss-network            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=rootpassword
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - ss-network          
networks:
    ss-network:              
    