version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - PORT=${PORT}
    container_name: lezione3_app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # password per root
      MYSQL_DATABASE: ${MYSQL_DB}                  # database da creare
      MYSQL_USER: ${MYSQL_USER}                    # utente NON root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # password dell'utente
    volumes:
      - db_data:/var/lib/mysql
    container_name: lezione3_db

volumes:
  db_data:
