version: "3.8"

services:
  app:
    build: app/.
    container_name: node_app
    ports:
      - "80:3000"
    depends_on:
      - redis
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: redis_server
    volumes:
      - redis-data:/data
    networks:
      - appnet

networks:
  appnet:

volumes:
  redis-data:
