version: '3.9'
services:
  app:
    build: ./server
    container_name: ssoftware_test_my_v_hostfolder_node
    image: ssoftware/test/my_v_hostfolder_node_image:latest
    #vendor / progetto : tag
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=testdb
      - JWT_SECRET=supersecret
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: ssoftware_test_my_v_hostfolder_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ssoftware_test_my_v_hostfolder_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8080:80"
    depends_on:
      - db
